# Generated by Django 4.1.5 on 2023-02-08 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mac', models.GenericIPAddressField()),
                ('network_name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('logged_at', models.DateTimeField()),
                ('uptime', models.IntegerField()),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
