# Generated by Django 4.1.5 on 2023-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='last_seen',
            field=models.DateField(null=True),
        ),
    ]
