# Generated by Django 4.1.5 on 2023-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_network_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
