# Generated by Django 4.1.5 on 2023-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_network_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='last_seen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='network',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
