# Generated by Django 4.1.5 on 2023-02-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_alter_network_last_seen_alter_network_logged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='uptime',
            field=models.BigIntegerField(),
        ),
    ]
