# Generated by Django 4.1.5 on 2023-02-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_alter_network_uptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='network',
            name='uptime',
        ),
    ]
