# Generated by Django 4.1.5 on 2023-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_remove_network_last_seen_remove_network_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
